# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: postgresql
#   database: ed_project_development 
#   host: localhost

development:

  adapter: postgresql
  database: ed_project_development 
  host: localhost
  pool: 5
  timeout: 5000


test:

  adapter: postgresql
  database: ed_project_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ed_project_production
  pool: 5
  timeout: 5000